name: Build & Deploy to EC2 using ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1 - Checkout Repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2 - Configure AWS Credentials
    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # Step 3 - Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 4 - Build & Push Docker Image to ECR
    - name: Build & Push Docker Image
      run: |
        REPO=378766468379.dkr.ecr.eu-north-1.amazonaws.com/cry-back
        TAG=latest

        echo "Building Docker image..."
        docker build -t cry-back .

        echo "Tagging Docker image..."
        docker tag cry-back:latest $REPO:$TAG

        echo "Pushing image to ECR..."
        docker push $REPO:$TAG

    # Step 5 - SSH to EC2 & Deploy Container
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          REPO=378766468379.dkr.ecr.eu-north-1.amazonaws.com/cry-back
          TAG=latest

          echo "Logging into ECR..."
          aws ecr get-login-password --region eu-north-1 \
            | docker login --username AWS --password-stdin $REPO

          echo "Pulling latest Docker image..."
          docker pull $REPO:$TAG

          echo "Stopping old container..."
          docker stop cry-back || true
          docker rm cry-back || true

          echo "Starting new container..."
          docker run -d --name cry-back -p 80:80 $REPO:$TAG

          echo "Deployment Completed Successfully!"
