name: Build, Push to ECR & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build and push Docker image
    - name: Build & Push Docker Image
    run: |
      IMAGE_TAG=latest
      REPO_URI=378766468379.dkr.ecr.eu-north-1.amazonaws.com/cry-back

      echo "Building Docker image..."
      docker build -t cry-back .

      echo "Tagging image..."
      docker tag cry-back:latest $REPO_URI:$IMAGE_TAG

      echo "Pushing to ECR..."
      docker push $REPO_URI:$IMAGE_TAG

    # SSH into EC2 and deploy container
    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Logging in to ECR..."
          aws ecr get-login-password --region eu-north-1 \
            | docker login --username AWS --password-stdin 378766468379.dkr.ecr.eu-north-1.amazonaws.com

          echo "Pull latest image..."
          docker pull 378766468379.dkr.ecr.eu-north-1.amazonaws.com/cry-back:latest

          echo "Stop old container..."
          docker stop cry-back || true
          docker rm cry-back || true

          echo "Start new container..."
          docker run -d --name cry-back -p 80:80 \
            378766468379.dkr.ecr.eu-north-1.amazonaws.com/cry-back:latest
